#! /bin/sh

# When refreshing bspwm, this will remove all previous rules (bad stuff will happen if not <- said the internet)
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
xmodmap ~/.Xmodmap &
xbindkeys
xrdb ~/.Xresources
wmname LG3D
xsetroot -cursor_name left_ptr

[ ! -f /usr/bin/picom ] || picom &

if [ "$WORK" ]; then
  if [ "$(bspc query -M | wc -l)" -gt "1" ]; then
    autorandr_profile='dell_widescreen_dockingstation'
  fi
else
  autorandr_profile=$(autorandr --detected)
fi

remove_disable_monitors_and_reorder() {
  bspc config remove_disabled_monitors true
  bspc config remove_unplugged_monitors true
  "$HOME/.config/bspwm/scripts/bspwm.reorder"
}

case $autorandr_profile in
  'default')
    autorandr --load default
    sleep 1
    remove_disable_monitors_and_reorder
    "$HOME/.config/polybar/launch-config.sh" default
    "$HOME/.config/bspwm/scripts/start-applications.default"
  ;;
  'home_widescreen_dockingstation')
    # "$HOME/.screenlayout/screenlayout_1.sh"
    # sleep 1
    "$HOME/.screenlayout/screenlayout_2.sh"
    remove_disable_monitors_and_reorder
    "$HOME/.config/polybar/launch-config.sh" widescreen
    "$HOME/.config/bspwm/scripts/start-applications.widescreen"
  ;;
  'dell_widescreen_dockingstation')
    # "$HOME/.screenlayout/screenlayout_1.sh"
    # sleep 1
    "$HOME/.screenlayout/screenlayout_2.sh"
    remove_disable_monitors_and_reorder
    "$HOME/.config/polybar/launch-config.sh" widescreen
    "$HOME/.config/bspwm/scripts/start-applications.widescreen"
  ;;
  'home_widescreen')
    autorandr --change
    remove_disable_monitors_and_reorder
    "$HOME/.config/polybar/launch-config.sh" widescreen
    "$HOME/.config/bspwm/scripts/start-applications.widescreen"
  ;;
  *)
    autorandr --load default
    remove_disable_monitors_and_reorder
    "$HOME/.config/polybar/launch-config.sh" default
    "$HOME/.config/bspwm/scripts/start-applications.default"
  ;;
esac

# Applets
#xfce4-power-manager &
blueman-applet &
flameshot &
enpass -minimize &
nm-applet &

# bspwm
bspc config border_width         4
bspc config window_gap           9

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

# Colors
bspc config focused_border_color "#6A1B9A"

# Set border colors
bspc config normal_border_color "#1a1b26"
# bspc config normal_border_color "$color1"
bspc config active_border_color "#9a7ecc"
# bspc config active_border_color "$color2"
bspc config presel_feedback_color "#6A1B9A"
#bspc config presel_feedback_color "$color1"

feh --bg-fill ~/.config/background.jpg
~/.config/bspwm/scripts/start-listener.sh &

### Persistent layout rules
# Delete Rules so we can start where we want
#sleep 3 # Sleep 3 seconds so the rules are active while the programs are starting
#bspc rule -r "*"
bspc rule -a gnome-calculator state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
